### ISSUE TITLE
Working group for ABIDE dataset

### ISSUE THREAD

**Issue by Elise-douard** [brainhack-school2020/mschoettner_fMRI-ML#8]
Hello! 

Really interesting project! 
I saw that other people may work with ABIDE to predict ASD/controls categories. 
Did you had a chance to discuss with other student to create an ABIDE-team?
eg : @anproulx wanted to work on connectivity with this dataset :) 

have a nice BHS !

**Comment by mschoettner** [comment]
Hey Elise,

yeah, we actually made a team on Github with @emilyemchen and @guenounz ! It's @brainhack-school2020/abide-team
